In [6]:
# Question 1
import numpy as np
a = np.array([1,2,3])
b= np.array([[1],[2],[3]])
print("The correct option is A:\n",a+b)

The correct option is A:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [9]:
#question 2
arr = np.arange(12).reshape(3,4)
print(arr)
print("The correct option is A:\n",arr[1:3, 1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The correct option is A:
 [[ 5  6]
 [ 9 10]]


In [10]:
# question 3
arr = np.array([-2,-1,0,1,2])
arr[arr<0]=(0)
arr

array([0, 0, 0, 1, 2])

In [11]:
# question 4

matrix = np.array ([[1, np.nan, 3], [4, 5, np.nan]])
row_mean = np.nanmean(matrix, axis=1)
print(row_mean)

[2.  4.5]


In [13]:
# question 5
data = np.array([10, 20, 30, 40])
idx = np.array([True, False, True, False])
print("The correct option is A:\n",data[idx])


The correct option is A:
 [10 30]


In [14]:
#question 6 
import pandas as pd
data = {'Name':['Alice','Bob','Charlie'], 'Age':[25,30,35]}
ind = [100,101,102]
op = pd.DataFrame(data, index=ind)
print(op)


Name  Age
100    Alice   25
101      Bob   30
102  Charlie   35

In [15]:
#questio 7
df = pd.DataFrame({'A': [1, 2, np.nan], 'B': [np.nan, 5, 6]})
print(df)
meanB=df['B'].mean()
print(meanB)
df['B']=df['B'].replace(np.nan , meanB)
print(df)

     A    B
0  1.0  NaN
1  2.0  5.0
2  NaN  6.0
5.5
     A    B
0  1.0  5.5
1  2.0  5.0
2  NaN  6.0


In [16]:
#question 8
df = pd.DataFrame({
    'Region': ['North', 'South', 'North', 'South'],
    'Sales': [100, 200, 150, 250],
    'Profit': [20, 30, 25, 40]})
df1 =  df.groupby('Region').agg({ 'Sales': 'sum', 'Profit': 'mean'}).reset_index
print(df1)

<bound method DataFrame.reset_index of         Sales  Profit
Region               
North     250    22.5
South     450    35.0>


In [17]:
#question 9
orders = pd.DataFrame({'order_id': [1, 2], 'cust_id': [101, 102]})
customers = pd.DataFrame({'cust_id': [101, 103], 'name': ['Alice', 'Bob']})
m1 = pd.merge(orders,customers,on='cust_id', how='left')
print(m1)

   order_id  cust_id   name
0         1      101  Alice
1         2      102    NaN


In [25]:
# question 10
df = pd.DataFrame({
    'Date': ['2023-01-05', '2023-01-15', '2023-02-10'],
    'Value': [10, 20, 30]})
print(df)
df['Date']=pd.to_datetime(df['Date'])
print(df.resample('ME', on='Date').sum())

         Date  Value
0  2023-01-05     10
1  2023-01-15     20
2  2023-02-10     30
            Value
Date             
2023-01-31     30
2023-02-28     30
